# For more information: https://github.com/julien-r44/adonis-sail
services:
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${MAILHOG_PORT:-1025}:1025'
      - '${MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail


networks:
  sail:
    driver: bridge


